type User {
  username: String!
  email: String! @unique
  resumes: [Resume] @relation
  confirmed: Boolean
	jobTitle: String
  bio: String
}

type Resume {
  user: User
  jobTitle: String
  bio: String
  title: String
  priority: Int
  categories: [Category] @relation
  template: Template @relation
  contactInfo: [ContactInfo] @relation
  layout: [Layout] @relation
}

type Category {
  resume: Resume
  name: String
  priority: Int
  items: [Item] @relation
}

type Item {
  category: Category
  title: String
  location: String
  description: String
  from: String
  to: String
  priority: Int
}

type ContactInfo {
  resume: Resume
  name: String
  value: String
  priority: Int
}

type Template {
  name: String
  style: String
	sidebar: Int
}

type Layout {
  resume: Resume
  name: String
  value: String
}

type Query {
  users: [User]
	usersByConfirmStatus(confirmed: Boolean!): [User]
  userByEmail(email: String!): User
  resumeByTitle(title: String!): Resume
  templates: [Template]
}
